import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import SessionAuth from "@/components/globals/SessionAuth";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full ">
      <body className={cn(" h-full", inter.className)}>
        <SessionAuth>
          <main className="h-full flex">
            <div className="w-full">{children}</div>
          </main>
        </SessionAuth>
        <Toaster />
      </body>
    </html>
  );
}
