import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/globals/Navbar";
import SideBar from "@/components/globals/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={cn("min-h-screen h-screen", inter.className)}>
          <Navbar />
          <main className="h-full flex">
            <SideBar />
            <div className="w-full">{children}</div>
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
